# config file version
apiVersion: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: TDengine
  # <string, required> datasource type. Required
  type: tdengine-datasource
  # <string, required> access mode. direct or proxy. Required
  # <int> org id. will defauto orgId 1 if not specified
  orgId: 1
  # <string> url
  url: $TDENGINE_API
  # <string> database user, if used
  user: $TDENGINE_USER
  # <bool> enable/disable basic auth
  basicAuth: true
#  withCredentials:
  # <bool> mark as default datasource. Max one per org
  isDefault: true
  # <map> fields that will be converted to json and stored in json_data
  secureJsonData:
    timeInterval: "5s"
    url: $TDENGINE_API
    # <string> database user, if used
    user: $TDENGINE_USER
    # <string> database password, if used
    password: $TDENGINE_PASS
    basicAuth: "${TDENGINE_BASIC_AUTH}"
    # Sms notification webhook support
    aliSmsAccessKeyId: $SMS_ACCESS_KEY_ID
    aliSmsAccessKeySecret: $SMS_ACCESS_KEY_SECRET
    aliSmsSignName: $SMS_SIGN_NAME
    aliSmsTemplateCode: $SMS_TEMPLATE_CODE
    aliSmsTemplateParam: $SMS_TEMPLATE_PARAM
    aliSmsPhoneNumbersList: $SMS_PHONE_NUMBERS
    aliSmsListenAddr: ${SMS_LISTEN_ADDR}
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
