name: "Release PR Merged"

on:
  pull_request:
    branches:
    - master
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'release:')
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Extract version
        id: extract-version
        run: |
          version=$(echo "${{ github.event.pull_request.title }}" | grep -o -P '(\d+\.\d+\.\d+)(-\S+)?')
          echo $version
          echo ::set-output name=version::$version
      - name: Version bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/release.sh ${{ steps.extract-version.outputs.version }}
